### ISSUE TITLE
Unable to visualize the results from the checkpoint

### ISSUE THREAD

**Issue by arunumd** [kentsyx/pointnet-pytorch#5]
I am trying to visualize the results of **ShapeNet part Segmentation**

I followed the mentioned steps of downloading the data, unzipping it, and then ran the following command for training a model :
`python train_seg.py -dset shapenet16 -r shapenet_root_dir -np number_of_points_to_sample`

The training was successful :
```
epoch 100: 101/106 | train loss: 0.139513 | train acc: 0.949703 | train iou: 0.904224
epoch 100: 102/106 | train loss: 0.105664 | train acc: 0.961766 | train iou: 0.926347
epoch 100: 103/106 | train loss: 0.129393 | train acc: 0.950281 | train iou: 0.905272
epoch 100: 104/106 | train loss: 0.126673 | train acc: 0.950328 | train iou: 0.905357
epoch 100: 105/106 | train loss: 0.129589 | train acc: 0.953500 | train iou: 0.911132
epoch 100: 106/106 | train loss: 0.162046 | train acc: 0.321937 | train iou: 0.191851
epoch 100 | mean train acc: 0.942338 | mean train IoU: 0.894963
epoch 100 | mean test acc: 0.927583 | mean test IoU: 0.865400
```

In order to visualize the results, when I run the `show_seg.py` after doing `sh build.sh` I get an error like below :
```
model 0/375
('number of classes', 4)
Traceback (most recent call last):
  File "show_seg.py", line 46, in <module>
    classifier.load_state_dict(torch.load(opt.model))
  File "/home/arun/anaconda3/envs/deep_learning2.7/lib/python2.7/site-packages/torch/serialization.py", line 381, in load
    f = open(f, 'rb')
IOError: [Errno 2] No such file or directory: ''
```
It seems like the checkpoint could not be loaded.

**Comment by arunumd** [comment]
Fixed the issue by giving the location of a model path like this :
`parser.add_argument('--model', type=str, default='/media/arun/c4e1387f-ed39-4119-8bde-05b000c73e3e/lost+found/arun/pointnet-pytorch/checkpoints/shapenet16_model_99.pth', help='model path')` in both `show_seg.py` and `show_seg_s3d.py`
